### ISSUE TITLE
Get IOS running - Analytics error

### ISSUE THREAD

**Issue by blumanski** [fullstackreact/react-native-firestack#65]
Lexical or Preprocessor Issue Group

I work of the master branch.

Xcode errors

    #import <FirebaseCore/FIRAnalyticsConfiguration.h>
    include of non-modular header inside framework module FireBaseAnalytics

    /.........../ios/Pods/FirebaseAnalytics/Frameworks/frameworks/FirebaseAnalytics.framework/Headers/FIRAnalyticsConfiguration.h:1:9: Include of non-modular header inside framework module 'FirebaseAnalytics'

    /............./node_modules/react-native-firestack/ios/Firestack/FirestackAnalytics.m:13:9: While     building module 'FirebaseAnalytics' imported from /Applications/XAMPP/xamppfiles/htdocs/react/stockalert/node_modules/react-native-firestack/ios/Firestack/FirestackAnalytics.m:13:

    /.........../ios/Pods/FirebaseAnalytics/Frameworks/frameworks/FirebaseAnalytics.framework/Headers/FirebaseAnalytics.h:5:9: In file included from ../../../ios/Pods/FirebaseAnalytics/Frameworks/frameworks/FirebaseAnalytics.framework/Headers/FirebaseAnalytics.h:5:

**Comment by jsappme** [comment]
+1

**Comment by blumanski** [comment]
@auser 
Today I was able to build for IOS which is great :-)

But the app is not running on ios, its crashing with the error below
emulator and iphone tested.

    ExceptionsManager.js:82 Exception 'Failed to get default FIRDatabase instance. 
    Must call FIRApp.configure() before using FIRDatabase.' was thrown while invoking 
    onOnce on  target     FirestackDatabase with params (
    "/marketAlerts/62D9781D-FF12-448B-B65E-270F6649DB5E",
        (
    ),
    value,
    3
)

So, what ever you have changed, it's getting close.

**Comment by jsappme** [comment]
I fixed this by uncomment the "use_framework!" line in the podfile.
and running pod install again
H
 🎉

**Comment by blumanski** [comment]
That didn't work for me....

I have installed a fresh app with newest versions, uncommented use_frameworks, still not working on ios with the same error as above.

If I use cloudMessage stuff in the code, the app is crashing right after start.
More testing....

**Comment by blumanski** [comment]
That looks like the right answer...

    http://stackoverflow.com/questions/37334323/the-default-app-has-not-been-configured-yet

**Comment by jsappme** [comment]
Make sure you have 'Firebase/Analytics' on your podfile, here is mine:

target 'Fishii' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
 use_frameworks!

  # Pods for Fishii

  target 'FishiiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

[
  'Firebase',
  'Firebase/Core',
  'Firebase/Auth',
  'Firebase/Storage',
  'Firebase/Database',
  'Firebase/RemoteConfig',
  'Firebase/Analytics',
  'Firebase/Messaging'
].each do |lib|
  pod lib
end

**Comment by blumanski** [comment]
Lol, I found the problem...
I had to drag the "GoogleService-Info.plist" file into xcode...

Thanks anyway :-)

**Comment by gemfile** [comment]
I resolved the same way with blumanski.

**Comment by calitbk** [comment]
The same way with blumanski. drag into xcode instead of into directory in finder or visual studio code (i use this ide)
